---
name: "Setup Workspace"
description: "Sets up CI for running development functions"
runs:
  using: "composite"
  steps:
    - name: Set up Golang
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install Go modules
      shell: bash
      run: |
        go mod tidy
