name: Production Release

on:
  push:
    branches:
      - main
    paths:
      - "specs.json"

jobs:
  verify:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run workspace setup
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: |
          just test

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs: verify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Set version
        id: set-version
        run: |
          VERSION=$(jq -r .version specs.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install Github CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Build binary
        id: build-binary
        run: |
          just tidy
          go mod download all
          mkdir -p build/linux-amd64 build/darwin-amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${VERSION}" -o ./build/linux-amd64/muxingbird main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${VERSION}" -o ./build/darwin-amd64/muxingbird main.go
          echo "Created binary builds!"

      - name: Create archive
        run: |
          mkdir -p release
          tar -czvf release/muxingbird-${{ env.VERSION }}-linux-amd64.tar.gz -C ./build/linux-amd64 muxingbird
          tar -czvf release/muxingbird-${{ env.VERSION }}-darwin-amd64.tar.gz -C ./build/darwin-amd64 muxingbird

      - name: Create Github release
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: |
          gh release create "${{ env.VERSION }}" \
            release/muxingbird-${{ env.VERSION }}-linux-amd64.tar.gz \
            release/muxingbird-${{ env.VERSION }}-darwin-amd64.tar.gz \
            --notes-file ".github/releases/${{ env.VERSION }}.md"

      - name: Create release job summary
        if: success()
        run: |
          cat .github/releases/${{ env.VERSION }}.md >> $GITHUB_STEP_SUMMARY
